remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "AutoGluon: Empowering (Multimodal) AutoML for the Next 10 Million Users"
description: "NeurIPS 2022,  New Orleans Convention Center, 2:00pm CST Nov 28th, Room 293."
